"""initial

Revision ID: 32d0a86858a2
Revises: 
Create Date: 2026-03-16 09:11:28.350749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '32d0a86858a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            CREATE TYPE enrollmentstatus AS ENUM (
                'PASSED',
                'IN_PROGRESS',
                'WITHDRAWN',
                'FAILED',
                'AUDIT',
                'INCOMPLETE'
            );
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END
        $$;
        """
    )
    op.create_table('courses',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('ects', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pass_grade', sa.String(), nullable=True),
    sa.Column('school', sa.String(length=32), nullable=True),
    sa.Column('academic_level', sa.String(length=16), nullable=True),
    sa.Column('section', sa.String(length=16), nullable=True),
    sa.Column('credits_us', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('days', sa.String(length=64), nullable=True),
    sa.Column('meeting_time', sa.String(length=64), nullable=True),
    sa.Column('enrolled', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.Text(), nullable=True),
    sa.Column('room', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'level', name='uq_courses_code_level')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('study_year', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('total_credits_earned', sa.Integer(), nullable=True),
    sa.Column('total_credits_enrolled', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('enrollments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('grade_points', sa.Float(), nullable=True),
    sa.Column(
        'status',
        postgresql.ENUM(
            'PASSED',
            'IN_PROGRESS',
            'WITHDRAWN',
            'FAILED',
            'AUDIT',
            'INCOMPLETE',
            name='enrollmentstatus',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', 'semester', name='uq_enrollment')
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.execute("DROP TYPE IF EXISTS enrollmentstatus")
    # ### end Alembic commands ###
